#!/bin/sh

[ -f "/etc/init.d/${1}" ] || {
	echo "service "'"'"${1}"'"'" not found, the following services are available:"

	if [ -z "${1}" ]; then
		ls --color=auto "/etc/init.d"
	else
		ls "/etc/init.d" |grep --color=auto "^${1}" || \
		ls "/etc/init.d" |grep --color=auto "${1}" || \
		ls --color=auto "/etc/init.d"
	fi

	return 1
}

/etc/init.d/$@

